// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: shipping/shipping.proto

package shipping

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShippingItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductCode   string                 `protobuf:"bytes,1,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShippingItem) Reset() {
	*x = ShippingItem{}
	mi := &file_shipping_shipping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShippingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShippingItem) ProtoMessage() {}

func (x *ShippingItem) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_shipping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShippingItem.ProtoReflect.Descriptor instead.
func (*ShippingItem) Descriptor() ([]byte, []int) {
	return file_shipping_shipping_proto_rawDescGZIP(), []int{0}
}

func (x *ShippingItem) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *ShippingItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateShippingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Items         []*ShippingItem        `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShippingRequest) Reset() {
	*x = CreateShippingRequest{}
	mi := &file_shipping_shipping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShippingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShippingRequest) ProtoMessage() {}

func (x *CreateShippingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_shipping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShippingRequest.ProtoReflect.Descriptor instead.
func (*CreateShippingRequest) Descriptor() ([]byte, []int) {
	return file_shipping_shipping_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShippingRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateShippingRequest) GetItems() []*ShippingItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateShippingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EtaDays       int32                  `protobuf:"varint,1,opt,name=eta_days,json=etaDays,proto3" json:"eta_days,omitempty"` // prazo de entrega em dias
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShippingResponse) Reset() {
	*x = CreateShippingResponse{}
	mi := &file_shipping_shipping_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShippingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShippingResponse) ProtoMessage() {}

func (x *CreateShippingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shipping_shipping_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShippingResponse.ProtoReflect.Descriptor instead.
func (*CreateShippingResponse) Descriptor() ([]byte, []int) {
	return file_shipping_shipping_proto_rawDescGZIP(), []int{2}
}

func (x *CreateShippingResponse) GetEtaDays() int32 {
	if x != nil {
		return x.EtaDays
	}
	return 0
}

var File_shipping_shipping_proto protoreflect.FileDescriptor

const file_shipping_shipping_proto_rawDesc = "" +
	"\n" +
	"\x17shipping/shipping.proto\x12\bshipping\"M\n" +
	"\fShippingItem\x12!\n" +
	"\fproduct_code\x18\x01 \x01(\tR\vproductCode\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"`\n" +
	"\x15CreateShippingRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12,\n" +
	"\x05items\x18\x02 \x03(\v2\x16.shipping.ShippingItemR\x05items\"3\n" +
	"\x16CreateShippingResponse\x12\x19\n" +
	"\beta_days\x18\x01 \x01(\x05R\aetaDays2W\n" +
	"\bShipping\x12K\n" +
	"\x06Create\x12\x1f.shipping.CreateShippingRequest\x1a .shipping.CreateShippingResponseBHZFgithub.com/victoralves475/microservices-proto/golang/shipping;shippingb\x06proto3"

var (
	file_shipping_shipping_proto_rawDescOnce sync.Once
	file_shipping_shipping_proto_rawDescData []byte
)

func file_shipping_shipping_proto_rawDescGZIP() []byte {
	file_shipping_shipping_proto_rawDescOnce.Do(func() {
		file_shipping_shipping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shipping_shipping_proto_rawDesc), len(file_shipping_shipping_proto_rawDesc)))
	})
	return file_shipping_shipping_proto_rawDescData
}

var file_shipping_shipping_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_shipping_shipping_proto_goTypes = []any{
	(*ShippingItem)(nil),           // 0: shipping.ShippingItem
	(*CreateShippingRequest)(nil),  // 1: shipping.CreateShippingRequest
	(*CreateShippingResponse)(nil), // 2: shipping.CreateShippingResponse
}
var file_shipping_shipping_proto_depIdxs = []int32{
	0, // 0: shipping.CreateShippingRequest.items:type_name -> shipping.ShippingItem
	1, // 1: shipping.Shipping.Create:input_type -> shipping.CreateShippingRequest
	2, // 2: shipping.Shipping.Create:output_type -> shipping.CreateShippingResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_shipping_shipping_proto_init() }
func file_shipping_shipping_proto_init() {
	if File_shipping_shipping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shipping_shipping_proto_rawDesc), len(file_shipping_shipping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shipping_shipping_proto_goTypes,
		DependencyIndexes: file_shipping_shipping_proto_depIdxs,
		MessageInfos:      file_shipping_shipping_proto_msgTypes,
	}.Build()
	File_shipping_shipping_proto = out.File
	file_shipping_shipping_proto_goTypes = nil
	file_shipping_shipping_proto_depIdxs = nil
}
